services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik/dynamic"
      - "./traefik/acme.json:/letsencrypt/acme.json"
    networks:
      - stf-net
    

  rethinkdb:
    image: rethinkdb:2.4.2
    container_name: rethinkdb
    volumes:
      - ./rethinkdb-data:/data
    networks:
      - stf-net

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_REDIRECT_URL=https://${DOMAIN}/oauth2/callback
      - OAUTH2_PROXY_COOKIE_NAME=ssid
      - OAUTH2_PROXY_UPSTREAMS=http://stf-api:7100  
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_PROXY_WEBSOCKETS=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.oauth.entrypoints=websecure"
      - "traefik.http.routers.oauth.tls.certresolver=le"
      - "traefik.http.services.oauth.loadbalancer.server.port=4180"
      
    networks:
      - stf-net

  stf-api:
    image: devicefarmer/stf:latest
    ports:
      - "7100:7100"
      - "7251:7251"
      - "7271:7271"
    command: >
      stf api --port 7100 
      --connect-sub tcp://stf-app:7250 
      --connect-push tcp://stf-app:7270 
      --connect-sub-dev tcp://0.0.0.0:7251 
      --connect-push-dev tcp://0.0.0.0:7271 
      --secret ${STF_SECRET}
      
    environment:
        - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stf-api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.stf-api.entrypoints=websecure"
      - "traefik.http.routers.stf-api.tls.certresolver=le"
      - "traefik.http.routers.stf-api.middlewares=forward-auth"
      - "traefik.http.routers.stf-api.service=stf-api"
      - "traefik.http.services.stf-api.loadbalancer.server.port=7100"
      
    
      
    depends_on:
      - rethinkdb
    networks:
      - stf-net

  stf-app:
    image: devicefarmer/stf:latest
    # ports:
      # - "7101:7101"
      # - "7250:7250"
      # - "7270:7270"
    command: >
      stf app --port 7101 
      --auth-url /oauth2/auth
      --websocket-url "wss://${DOMAIN}/d/websocket"
      

      
    environment:
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_APP_SECRET=${STF_SECRET}
      # - STF_APP_PUBLIC_IP=https://${DOMAIN}/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stf.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.stf.entrypoints=websecure"
      - "traefik.http.routers.stf.tls.certresolver=le"
      - "traefik.http.routers.stf.service=stf"
      - "traefik.http.services.stf.loadbalancer.server.port=7101"
      - "traefik.http.routers.stf.middlewares=fix-https,forward-auth"
      - "traefik.http.middlewares.fix-https.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.forward-auth.forwardauth.address=https://${DOMAIN}/oauth2/auth"
      - "traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email"
      - "traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true"
    networks:
      - stf-net

  stf-processor:
    image: devicefarmer/stf:latest
    command: >
      stf processor 
      --connect-app-dealer tcp://0.0.0.0:7260 
      --connect-dev-dealer tcp://0.0.0.0:7261
    environment:
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      
    depends_on:
      - stf-api
    networks:
      - stf-net

  stf-storage-temp:
    image: devicefarmer/stf:latest
    command: stf storage-temp
    networks:
      - stf-net

  stf-storage-plugin-image:
    image: devicefarmer/stf:latest
    command: stf storage-plugin-image
    networks:
      - stf-net
    environment:
      - STF_STORAGE_PLUGIN_IMAGE_STORAGE_URL=http://stf-storage-temp:7102
    depends_on:
        - stf-storage-temp

  stf-websocket:
    image: devicefarmer/stf:latest
    ports:
      - "7110:7110"
    command: >
      stf websocket 
      --port 7110 
      --connect-sub tcp://stf-app:7250 
      --connect-push tcp://stf-app:7270  
      --secret ${STF_SECRET}
    environment:
      - STF_WEBSOCKET_STORAGE_URL=http://stf-storage-temp:7102
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
    networks:
      - stf-net

networks:
  stf-net:
    driver: bridge
